### PR TITLE
Helpers 2.1

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
@ericgaspar I pulled the version with your clean up (thanks!), and tested it out locally in addition to the tests. 

I seemed like I had to re-add back:
`sudo chmod -R u+rwX,g+rwX,o+r $install_dir/lichen-markdown/src` or otherwise this directory was not getting the write permissions the app needs (its a CMS that needs to read and write from that directory)

while I was there I also noticed a bug, and fixed my nginx config to use the php-fpm config specific for this app, rather than the generic one for the system

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
@ericgaspar I'm confused why when I run "testme" it runs the test twice, once where it passes all the tests, and once where it fails. Is this a yunohost test-framework issue?

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
!testme

**Pull request merged**
